"""Port de persistance. Méthodes explicites, pas de dépôt générique."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from core.domain.model import BusinessContext, JobRun, JobSpec, Organization, Project


class CoreRepository(Protocol):
    def add_organization(self, organization: Organization) -> None: ...

    def get_organization(self, organization_id: UUID) -> Organization | None: ...

    def add_project(self, project: Project) -> None: ...

    def get_project(self, organization_id: UUID, project_id: UUID) -> Project | None: ...

    def add_business_context(self, context: BusinessContext) -> None: ...

    def get_business_context(self, organization_id: UUID, project_id: UUID) -> BusinessContext | None: ...

    def add_job_spec(self, spec: JobSpec) -> None: ...

    def get_job_spec(self, organization_id: UUID, project_id: UUID, job_spec_id: UUID) -> JobSpec | None: ...

    def add_job_run(self, run: JobRun) -> None: ...

    def get_job_run(self, organization_id: UUID, project_id: UUID, job_run_id: UUID) -> JobRun | None: ...
